[backend]
queues = 10
queue_slots = 10
days_range = 14

[queue_form]
fields = [
    { name = "name", type = "string", required = true },
    { name = "phone", type = "string", required = true },
    { name = "message", type = "string", required = true },
    { name = "timeslot", type = "string", required = true },
    { name = "timestamp", type = "string", required = true },
    { name = "queue_number", type = "number", required = true },
]
